// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.io.Serializable;
import net.eyelock.sakila.domain.FilmCategoryPK;

privileged aspect FilmCategoryPK_Roo_Serializable {
    
    declare parents: FilmCategoryPK implements Serializable;
    
    private static final long FilmCategoryPK.serialVersionUID = 1L;
    
}
