// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.io.Serializable;
import net.eyelock.sakila.domain.FilmActorPK;

privileged aspect FilmActorPK_Roo_Serializable {
    
    declare parents: FilmActorPK implements Serializable;
    
    private static final long FilmActorPK.serialVersionUID = 1L;
    
}
