// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.ActorDataOnDemand;
import net.eyelock.sakila.domain.ActorIntegrationTest;
import net.eyelock.sakila.repositories.ActorRepository;
import net.eyelock.sakila.services.ActorService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ActorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ActorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ActorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ActorIntegrationTest: @Transactional;
    
    @Autowired
    ActorDataOnDemand ActorIntegrationTest.dod;
    
    @Autowired
    ActorService ActorIntegrationTest.actorService;
    
    @Autowired
    ActorRepository ActorIntegrationTest.actorRepository;
    
    @Test
    public void ActorIntegrationTest.testCountAllActors() {
        Assert.assertNotNull("Data on demand for 'Actor' failed to initialize correctly", dod.getRandomActor());
        long count = actorService.countAllActors();
        Assert.assertTrue("Counter for 'Actor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ActorIntegrationTest.testFindActor() {
        Actor obj = dod.getRandomActor();
        Assert.assertNotNull("Data on demand for 'Actor' failed to initialize correctly", obj);
        Short id = obj.getActorId();
        Assert.assertNotNull("Data on demand for 'Actor' failed to provide an identifier", id);
        obj = actorService.findActor(id);
        Assert.assertNotNull("Find method for 'Actor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Actor' returned the incorrect identifier", id, obj.getActorId());
    }
    
    @Test
    public void ActorIntegrationTest.testFindAllActors() {
        Assert.assertNotNull("Data on demand for 'Actor' failed to initialize correctly", dod.getRandomActor());
        long count = actorService.countAllActors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Actor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Actor> result = actorService.findAllActors();
        Assert.assertNotNull("Find all method for 'Actor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Actor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ActorIntegrationTest.testFindActorEntries() {
        Assert.assertNotNull("Data on demand for 'Actor' failed to initialize correctly", dod.getRandomActor());
        long count = actorService.countAllActors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Actor> result = actorService.findActorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Actor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Actor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ActorIntegrationTest.testSaveActor() {
        Assert.assertNotNull("Data on demand for 'Actor' failed to initialize correctly", dod.getRandomActor());
        Actor obj = dod.getNewTransientActor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Actor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Actor' identifier to be null", obj.getActorId());
        try {
            actorService.saveActor(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        actorRepository.flush();
        Assert.assertNotNull("Expected 'Actor' identifier to no longer be null", obj.getActorId());
    }
    
    @Test
    public void ActorIntegrationTest.testDeleteActor() {
        Actor obj = dod.getRandomActor();
        Assert.assertNotNull("Data on demand for 'Actor' failed to initialize correctly", obj);
        Short id = obj.getActorId();
        Assert.assertNotNull("Data on demand for 'Actor' failed to provide an identifier", id);
        obj = actorService.findActor(id);
        actorService.deleteActor(obj);
        actorRepository.flush();
        Assert.assertNull("Failed to remove 'Actor' with identifier '" + id + "'", actorService.findActor(id));
    }
    
}
