// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.AddressDataOnDemand;
import net.eyelock.sakila.domain.AddressIntegrationTest;
import net.eyelock.sakila.repositories.AddressRepository;
import net.eyelock.sakila.services.AddressService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AddressIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AddressIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AddressIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AddressIntegrationTest: @Transactional;
    
    @Autowired
    AddressDataOnDemand AddressIntegrationTest.dod;
    
    @Autowired
    AddressService AddressIntegrationTest.addressService;
    
    @Autowired
    AddressRepository AddressIntegrationTest.addressRepository;
    
    @Test
    public void AddressIntegrationTest.testCountAllAddresses() {
        Assert.assertNotNull("Data on demand for 'Address' failed to initialize correctly", dod.getRandomAddress());
        long count = addressService.countAllAddresses();
        Assert.assertTrue("Counter for 'Address' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AddressIntegrationTest.testFindAddress() {
        Address obj = dod.getRandomAddress();
        Assert.assertNotNull("Data on demand for 'Address' failed to initialize correctly", obj);
        Short id = obj.getAddressId();
        Assert.assertNotNull("Data on demand for 'Address' failed to provide an identifier", id);
        obj = addressService.findAddress(id);
        Assert.assertNotNull("Find method for 'Address' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Address' returned the incorrect identifier", id, obj.getAddressId());
    }
    
    @Test
    public void AddressIntegrationTest.testFindAllAddresses() {
        Assert.assertNotNull("Data on demand for 'Address' failed to initialize correctly", dod.getRandomAddress());
        long count = addressService.countAllAddresses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Address', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Address> result = addressService.findAllAddresses();
        Assert.assertNotNull("Find all method for 'Address' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Address' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AddressIntegrationTest.testFindAddressEntries() {
        Assert.assertNotNull("Data on demand for 'Address' failed to initialize correctly", dod.getRandomAddress());
        long count = addressService.countAllAddresses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Address> result = addressService.findAddressEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Address' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Address' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AddressIntegrationTest.testSaveAddress() {
        Assert.assertNotNull("Data on demand for 'Address' failed to initialize correctly", dod.getRandomAddress());
        Address obj = dod.getNewTransientAddress(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Address' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Address' identifier to be null", obj.getAddressId());
        try {
            addressService.saveAddress(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        addressRepository.flush();
        Assert.assertNotNull("Expected 'Address' identifier to no longer be null", obj.getAddressId());
    }
    
    @Test
    public void AddressIntegrationTest.testDeleteAddress() {
        Address obj = dod.getRandomAddress();
        Assert.assertNotNull("Data on demand for 'Address' failed to initialize correctly", obj);
        Short id = obj.getAddressId();
        Assert.assertNotNull("Data on demand for 'Address' failed to provide an identifier", id);
        obj = addressService.findAddress(id);
        addressService.deleteAddress(obj);
        addressRepository.flush();
        Assert.assertNull("Failed to remove 'Address' with identifier '" + id + "'", addressService.findAddress(id));
    }
    
}
