// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.FilmDataOnDemand;
import net.eyelock.sakila.domain.FilmIntegrationTest;
import net.eyelock.sakila.repositories.FilmRepository;
import net.eyelock.sakila.services.FilmService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FilmIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FilmIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FilmIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FilmIntegrationTest: @Transactional;
    
    @Autowired
    FilmDataOnDemand FilmIntegrationTest.dod;
    
    @Autowired
    FilmService FilmIntegrationTest.filmService;
    
    @Autowired
    FilmRepository FilmIntegrationTest.filmRepository;
    
    @Test
    public void FilmIntegrationTest.testCountAllFilms() {
        Assert.assertNotNull("Data on demand for 'Film' failed to initialize correctly", dod.getRandomFilm());
        long count = filmService.countAllFilms();
        Assert.assertTrue("Counter for 'Film' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FilmIntegrationTest.testFindFilm() {
        Film obj = dod.getRandomFilm();
        Assert.assertNotNull("Data on demand for 'Film' failed to initialize correctly", obj);
        Short id = obj.getFilmId();
        Assert.assertNotNull("Data on demand for 'Film' failed to provide an identifier", id);
        obj = filmService.findFilm(id);
        Assert.assertNotNull("Find method for 'Film' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Film' returned the incorrect identifier", id, obj.getFilmId());
    }
    
    @Test
    public void FilmIntegrationTest.testFindAllFilms() {
        Assert.assertNotNull("Data on demand for 'Film' failed to initialize correctly", dod.getRandomFilm());
        long count = filmService.countAllFilms();
        Assert.assertTrue("Too expensive to perform a find all test for 'Film', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Film> result = filmService.findAllFilms();
        Assert.assertNotNull("Find all method for 'Film' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Film' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FilmIntegrationTest.testFindFilmEntries() {
        Assert.assertNotNull("Data on demand for 'Film' failed to initialize correctly", dod.getRandomFilm());
        long count = filmService.countAllFilms();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Film> result = filmService.findFilmEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Film' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Film' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FilmIntegrationTest.testSaveFilm() {
        Assert.assertNotNull("Data on demand for 'Film' failed to initialize correctly", dod.getRandomFilm());
        Film obj = dod.getNewTransientFilm(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Film' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Film' identifier to be null", obj.getFilmId());
        try {
            filmService.saveFilm(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        filmRepository.flush();
        Assert.assertNotNull("Expected 'Film' identifier to no longer be null", obj.getFilmId());
    }
    
    @Test
    public void FilmIntegrationTest.testDeleteFilm() {
        Film obj = dod.getRandomFilm();
        Assert.assertNotNull("Data on demand for 'Film' failed to initialize correctly", obj);
        Short id = obj.getFilmId();
        Assert.assertNotNull("Data on demand for 'Film' failed to provide an identifier", id);
        obj = filmService.findFilm(id);
        filmService.deleteFilm(obj);
        filmRepository.flush();
        Assert.assertNull("Failed to remove 'Film' with identifier '" + id + "'", filmService.findFilm(id));
    }
    
}
