// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.FilmCategoryDataOnDemand;
import net.eyelock.sakila.domain.FilmCategoryIntegrationTest;
import net.eyelock.sakila.domain.FilmCategoryPK;
import net.eyelock.sakila.repositories.FilmCategoryRepository;
import net.eyelock.sakila.services.FilmCategoryService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FilmCategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FilmCategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FilmCategoryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FilmCategoryIntegrationTest: @Transactional;
    
    @Autowired
    FilmCategoryDataOnDemand FilmCategoryIntegrationTest.dod;
    
    @Autowired
    FilmCategoryService FilmCategoryIntegrationTest.filmCategoryService;
    
    @Autowired
    FilmCategoryRepository FilmCategoryIntegrationTest.filmCategoryRepository;
    
    @Test
    public void FilmCategoryIntegrationTest.testCountAllFilmCategorys() {
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to initialize correctly", dod.getRandomFilmCategory());
        long count = filmCategoryService.countAllFilmCategorys();
        Assert.assertTrue("Counter for 'FilmCategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FilmCategoryIntegrationTest.testFindFilmCategory() {
        FilmCategory obj = dod.getRandomFilmCategory();
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to initialize correctly", obj);
        FilmCategoryPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to provide an identifier", id);
        obj = filmCategoryService.findFilmCategory(id);
        Assert.assertNotNull("Find method for 'FilmCategory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FilmCategory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FilmCategoryIntegrationTest.testFindAllFilmCategorys() {
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to initialize correctly", dod.getRandomFilmCategory());
        long count = filmCategoryService.countAllFilmCategorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'FilmCategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FilmCategory> result = filmCategoryService.findAllFilmCategorys();
        Assert.assertNotNull("Find all method for 'FilmCategory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FilmCategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FilmCategoryIntegrationTest.testFindFilmCategoryEntries() {
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to initialize correctly", dod.getRandomFilmCategory());
        long count = filmCategoryService.countAllFilmCategorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FilmCategory> result = filmCategoryService.findFilmCategoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FilmCategory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FilmCategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FilmCategoryIntegrationTest.testSaveFilmCategory() {
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to initialize correctly", dod.getRandomFilmCategory());
        FilmCategory obj = dod.getNewTransientFilmCategory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to provide a new transient entity", obj);
        try {
            filmCategoryService.saveFilmCategory(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        filmCategoryRepository.flush();
        Assert.assertNotNull("Expected 'FilmCategory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FilmCategoryIntegrationTest.testDeleteFilmCategory() {
        FilmCategory obj = dod.getRandomFilmCategory();
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to initialize correctly", obj);
        FilmCategoryPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FilmCategory' failed to provide an identifier", id);
        obj = filmCategoryService.findFilmCategory(id);
        filmCategoryService.deleteFilmCategory(obj);
        filmCategoryRepository.flush();
        Assert.assertNull("Failed to remove 'FilmCategory' with identifier '" + id + "'", filmCategoryService.findFilmCategory(id));
    }
    
}
