// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.Film;
import net.eyelock.sakila.domain.FilmDataOnDemand;
import net.eyelock.sakila.domain.Inventory;
import net.eyelock.sakila.domain.InventoryDataOnDemand;
import net.eyelock.sakila.domain.Store;
import net.eyelock.sakila.domain.StoreDataOnDemand;
import net.eyelock.sakila.repositories.InventoryRepository;
import net.eyelock.sakila.services.InventoryService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect InventoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InventoryDataOnDemand: @Component;
    
    private Random InventoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Inventory> InventoryDataOnDemand.data;
    
    @Autowired
    FilmDataOnDemand InventoryDataOnDemand.filmDataOnDemand;
    
    @Autowired
    StoreDataOnDemand InventoryDataOnDemand.storeDataOnDemand;
    
    @Autowired
    InventoryService InventoryDataOnDemand.inventoryService;
    
    @Autowired
    InventoryRepository InventoryDataOnDemand.inventoryRepository;
    
    public Inventory InventoryDataOnDemand.getNewTransientInventory(int index) {
        Inventory obj = new Inventory();
        setFilmId(obj, index);
        setLastUpdate(obj, index);
        setStoreId(obj, index);
        return obj;
    }
    
    public void InventoryDataOnDemand.setFilmId(Inventory obj, int index) {
        Film filmId = filmDataOnDemand.getRandomFilm();
        obj.setFilmId(filmId);
    }
    
    public void InventoryDataOnDemand.setLastUpdate(Inventory obj, int index) {
        Calendar lastUpdate = Calendar.getInstance();
        obj.setLastUpdate(lastUpdate);
    }
    
    public void InventoryDataOnDemand.setStoreId(Inventory obj, int index) {
        Store storeId = storeDataOnDemand.getRandomStore();
        obj.setStoreId(storeId);
    }
    
    public Inventory InventoryDataOnDemand.getSpecificInventory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Inventory obj = data.get(index);
        Integer id = obj.getInventoryId();
        return inventoryService.findInventory(id);
    }
    
    public Inventory InventoryDataOnDemand.getRandomInventory() {
        init();
        Inventory obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getInventoryId();
        return inventoryService.findInventory(id);
    }
    
    public boolean InventoryDataOnDemand.modifyInventory(Inventory obj) {
        return false;
    }
    
    public void InventoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = inventoryService.findInventoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Inventory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Inventory>();
        for (int i = 0; i < 10; i++) {
            Inventory obj = getNewTransientInventory(i);
            try {
                inventoryService.saveInventory(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            inventoryRepository.flush();
            data.add(obj);
        }
    }
    
}
