// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.InventoryDataOnDemand;
import net.eyelock.sakila.domain.InventoryIntegrationTest;
import net.eyelock.sakila.repositories.InventoryRepository;
import net.eyelock.sakila.services.InventoryService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InventoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InventoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InventoryIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: InventoryIntegrationTest: @Transactional;
    
    @Autowired
    InventoryDataOnDemand InventoryIntegrationTest.dod;
    
    @Autowired
    InventoryService InventoryIntegrationTest.inventoryService;
    
    @Autowired
    InventoryRepository InventoryIntegrationTest.inventoryRepository;
    
    @Test
    public void InventoryIntegrationTest.testCountAllInventorys() {
        Assert.assertNotNull("Data on demand for 'Inventory' failed to initialize correctly", dod.getRandomInventory());
        long count = inventoryService.countAllInventorys();
        Assert.assertTrue("Counter for 'Inventory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InventoryIntegrationTest.testFindInventory() {
        Inventory obj = dod.getRandomInventory();
        Assert.assertNotNull("Data on demand for 'Inventory' failed to initialize correctly", obj);
        Integer id = obj.getInventoryId();
        Assert.assertNotNull("Data on demand for 'Inventory' failed to provide an identifier", id);
        obj = inventoryService.findInventory(id);
        Assert.assertNotNull("Find method for 'Inventory' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Inventory' returned the incorrect identifier", id, obj.getInventoryId());
    }
    
    @Test
    public void InventoryIntegrationTest.testFindAllInventorys() {
        Assert.assertNotNull("Data on demand for 'Inventory' failed to initialize correctly", dod.getRandomInventory());
        long count = inventoryService.countAllInventorys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Inventory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Inventory> result = inventoryService.findAllInventorys();
        Assert.assertNotNull("Find all method for 'Inventory' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Inventory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InventoryIntegrationTest.testFindInventoryEntries() {
        Assert.assertNotNull("Data on demand for 'Inventory' failed to initialize correctly", dod.getRandomInventory());
        long count = inventoryService.countAllInventorys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Inventory> result = inventoryService.findInventoryEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Inventory' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Inventory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InventoryIntegrationTest.testSaveInventory() {
        Assert.assertNotNull("Data on demand for 'Inventory' failed to initialize correctly", dod.getRandomInventory());
        Inventory obj = dod.getNewTransientInventory(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Inventory' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Inventory' identifier to be null", obj.getInventoryId());
        try {
            inventoryService.saveInventory(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        inventoryRepository.flush();
        Assert.assertNotNull("Expected 'Inventory' identifier to no longer be null", obj.getInventoryId());
    }
    
    @Test
    public void InventoryIntegrationTest.testDeleteInventory() {
        Inventory obj = dod.getRandomInventory();
        Assert.assertNotNull("Data on demand for 'Inventory' failed to initialize correctly", obj);
        Integer id = obj.getInventoryId();
        Assert.assertNotNull("Data on demand for 'Inventory' failed to provide an identifier", id);
        obj = inventoryService.findInventory(id);
        inventoryService.deleteInventory(obj);
        inventoryRepository.flush();
        Assert.assertNull("Failed to remove 'Inventory' with identifier '" + id + "'", inventoryService.findInventory(id));
    }
    
}
