// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.Language;
import net.eyelock.sakila.domain.LanguageDataOnDemand;
import net.eyelock.sakila.repositories.LanguageRepository;
import net.eyelock.sakila.services.LanguageService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LanguageDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LanguageDataOnDemand: @Component;
    
    private Random LanguageDataOnDemand.rnd = new SecureRandom();
    
    private List<Language> LanguageDataOnDemand.data;
    
    @Autowired
    LanguageService LanguageDataOnDemand.languageService;
    
    @Autowired
    LanguageRepository LanguageDataOnDemand.languageRepository;
    
    public Language LanguageDataOnDemand.getNewTransientLanguage(int index) {
        Language obj = new Language();
        setLastUpdate(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void LanguageDataOnDemand.setLastUpdate(Language obj, int index) {
        Calendar lastUpdate = Calendar.getInstance();
        obj.setLastUpdate(lastUpdate);
    }
    
    public void LanguageDataOnDemand.setName(Language obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public Language LanguageDataOnDemand.getSpecificLanguage(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Language obj = data.get(index);
        Short id = obj.getLanguageId();
        return languageService.findLanguage(id);
    }
    
    public Language LanguageDataOnDemand.getRandomLanguage() {
        init();
        Language obj = data.get(rnd.nextInt(data.size()));
        Short id = obj.getLanguageId();
        return languageService.findLanguage(id);
    }
    
    public boolean LanguageDataOnDemand.modifyLanguage(Language obj) {
        return false;
    }
    
    public void LanguageDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = languageService.findLanguageEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Language' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Language>();
        for (int i = 0; i < 10; i++) {
            Language obj = getNewTransientLanguage(i);
            try {
                languageService.saveLanguage(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            languageRepository.flush();
            data.add(obj);
        }
    }
    
}
