// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.LanguageDataOnDemand;
import net.eyelock.sakila.domain.LanguageIntegrationTest;
import net.eyelock.sakila.repositories.LanguageRepository;
import net.eyelock.sakila.services.LanguageService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LanguageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LanguageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LanguageIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LanguageIntegrationTest: @Transactional;
    
    @Autowired
    LanguageDataOnDemand LanguageIntegrationTest.dod;
    
    @Autowired
    LanguageService LanguageIntegrationTest.languageService;
    
    @Autowired
    LanguageRepository LanguageIntegrationTest.languageRepository;
    
    @Test
    public void LanguageIntegrationTest.testCountAllLanguages() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        long count = languageService.countAllLanguages();
        Assert.assertTrue("Counter for 'Language' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LanguageIntegrationTest.testFindLanguage() {
        Language obj = dod.getRandomLanguage();
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", obj);
        Short id = obj.getLanguageId();
        Assert.assertNotNull("Data on demand for 'Language' failed to provide an identifier", id);
        obj = languageService.findLanguage(id);
        Assert.assertNotNull("Find method for 'Language' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Language' returned the incorrect identifier", id, obj.getLanguageId());
    }
    
    @Test
    public void LanguageIntegrationTest.testFindAllLanguages() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        long count = languageService.countAllLanguages();
        Assert.assertTrue("Too expensive to perform a find all test for 'Language', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Language> result = languageService.findAllLanguages();
        Assert.assertNotNull("Find all method for 'Language' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Language' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LanguageIntegrationTest.testFindLanguageEntries() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        long count = languageService.countAllLanguages();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Language> result = languageService.findLanguageEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Language' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Language' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LanguageIntegrationTest.testSaveLanguage() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        Language obj = dod.getNewTransientLanguage(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Language' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Language' identifier to be null", obj.getLanguageId());
        try {
            languageService.saveLanguage(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        languageRepository.flush();
        Assert.assertNotNull("Expected 'Language' identifier to no longer be null", obj.getLanguageId());
    }
    
    @Test
    public void LanguageIntegrationTest.testDeleteLanguage() {
        Language obj = dod.getRandomLanguage();
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", obj);
        Short id = obj.getLanguageId();
        Assert.assertNotNull("Data on demand for 'Language' failed to provide an identifier", id);
        obj = languageService.findLanguage(id);
        languageService.deleteLanguage(obj);
        languageRepository.flush();
        Assert.assertNull("Failed to remove 'Language' with identifier '" + id + "'", languageService.findLanguage(id));
    }
    
}
