// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import net.eyelock.sakila.domain.StaffDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StaffDataOnDemand_Roo_Configurable {
    
    declare @type: StaffDataOnDemand: @Configurable;
    
}
