// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.eyelock.sakila.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.eyelock.sakila.domain.Address;
import net.eyelock.sakila.domain.AddressDataOnDemand;
import net.eyelock.sakila.domain.Staff;
import net.eyelock.sakila.domain.StaffDataOnDemand;
import net.eyelock.sakila.domain.Store;
import net.eyelock.sakila.domain.StoreDataOnDemand;
import net.eyelock.sakila.repositories.StoreRepository;
import net.eyelock.sakila.services.StoreService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect StoreDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StoreDataOnDemand: @Component;
    
    private Random StoreDataOnDemand.rnd = new SecureRandom();
    
    private List<Store> StoreDataOnDemand.data;
    
    @Autowired
    AddressDataOnDemand StoreDataOnDemand.addressDataOnDemand;
    
    @Autowired
    StaffDataOnDemand StoreDataOnDemand.staffDataOnDemand;
    
    @Autowired
    StoreService StoreDataOnDemand.storeService;
    
    @Autowired
    StoreRepository StoreDataOnDemand.storeRepository;
    
    public Store StoreDataOnDemand.getNewTransientStore(int index) {
        Store obj = new Store();
        setAddressId(obj, index);
        setLastUpdate(obj, index);
        setManagerStaffId(obj, index);
        return obj;
    }
    
    public void StoreDataOnDemand.setAddressId(Store obj, int index) {
        Address addressId = addressDataOnDemand.getRandomAddress();
        obj.setAddressId(addressId);
    }
    
    public void StoreDataOnDemand.setLastUpdate(Store obj, int index) {
        Calendar lastUpdate = Calendar.getInstance();
        obj.setLastUpdate(lastUpdate);
    }
    
    public void StoreDataOnDemand.setManagerStaffId(Store obj, int index) {
        Staff managerStaffId = staffDataOnDemand.getRandomStaff();
        obj.setManagerStaffId(managerStaffId);
    }
    
    public Store StoreDataOnDemand.getSpecificStore(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Store obj = data.get(index);
        Short id = obj.getStoreId();
        return storeService.findStore(id);
    }
    
    public Store StoreDataOnDemand.getRandomStore() {
        init();
        Store obj = data.get(rnd.nextInt(data.size()));
        Short id = obj.getStoreId();
        return storeService.findStore(id);
    }
    
    public boolean StoreDataOnDemand.modifyStore(Store obj) {
        return false;
    }
    
    public void StoreDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = storeService.findStoreEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Store' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Store>();
        for (int i = 0; i < 10; i++) {
            Store obj = getNewTransientStore(i);
            try {
                storeService.saveStore(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            storeRepository.flush();
            data.add(obj);
        }
    }
    
}
